package telegram

import (
	"fmt"
	"strings"

	"github.com/deuswork/nintendoflow/pkg/db"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// PostArticle sends an article to the Telegram channel.
// If the article has an image, sendPhoto is used; otherwise sendMessage.
func PostArticle(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	if article.VideoURL != "" {
		video := tgbotapi.VideoConfig{
			BaseFile: tgbotapi.BaseFile{
				BaseChat: tgbotapi.BaseChat{ChannelUsername: channelID},
				File:     tgbotapi.FileURL(article.VideoURL),
			},
			Caption:   buildCaption(&article, 1024),
			ParseMode: "HTML",
		}
		if _, err := bot.Send(video); err == nil {
			return nil
		}

		// YouTube page URLs can fail in sendVideo because they are not direct file URLs.
		if err := sendTextWithVideoLink(bot, channelID, article); err == nil {
			return nil
		}
	}

	if article.ImageURL != "" {
		photo := tgbotapi.PhotoConfig{
			BaseFile: tgbotapi.BaseFile{
				BaseChat: tgbotapi.BaseChat{
					ChannelUsername: channelID,
				},
				File: tgbotapi.FileURL(article.ImageURL),
			},
			Caption:   buildCaption(&article, 1024),
			ParseMode: "HTML",
		}
		if _, err := bot.Send(photo); err != nil {
			// fallback to text-only
			return sendText(bot, channelID, article)
		}
		return nil
	}
	return sendText(bot, channelID, article)
}

func sendTextWithVideoLink(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	caption := buildCaption(&article, 3800)
	// Use an invisible link at the start of the message to trigger the link preview
	// without showing the messy URL text. We use html.EscapeString to ensure valid HTML.
	safeURL := strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(article.VideoURL, "&", "&amp;"), "<", "&lt;"), ">", "&gt;")
	invisibleLink := fmt.Sprintf(`<a href="%s">%s</a>`, safeURL, "\u200b")
	msg := tgbotapi.NewMessageToChannel(channelID, invisibleLink+caption)
	msg.ParseMode = "HTML"

	if _, err := bot.Send(msg); err != nil {
		return fmt.Errorf("telegram sendMessage with video link: %w", err)
	}
	return nil
}

func sendText(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	msg := tgbotapi.NewMessageToChannel(channelID, buildCaption(&article, 4096))
	msg.ParseMode = "HTML"
	if _, err := bot.Send(msg); err != nil {
		return fmt.Errorf("telegram sendMessage: %w", err)
	}
	return nil
}

// buildCaption forms the final post text based on source type.
func buildCaption(article *db.Article, maxLen int) string {
	var prefix string
	switch article.SourceType {
	case "official":
		prefix = "📢 <b>ОФІЦІЙНО</b>\n\n"
	case "insider":
		prefix = "🕵️ <i>Інсайд</i>\n\n"
	case "aggregator":
		prefix = "📡 <i>Чутки</i>\n\n"
	default:
		prefix = ""
	}

	body := stripSourceFooter(article.BodyUA)
	full := prefix + body
	runes := []rune(full)
	if len(runes) <= maxLen {
		return full
	}

	bodyRunes := []rune(body)
	allowed := maxLen - len([]rune(prefix)) - 3
	if allowed > 0 && allowed < len(bodyRunes) {
		return prefix + string(bodyRunes[:allowed]) + "..."
	}
	return string(runes[:maxLen])
}

// stripSourceFooter removes stray inline-link lines (🔗) left from older
// bot versions. "Джерело:" lines are now generated by the AI and are kept.
func stripSourceFooter(body string) string {
	lines := strings.Split(body, "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "🔗") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}
