package telegram

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strings"

	"github.com/deuswork/nintendoflow/pkg/db"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// PostArticle sends an article to the Telegram channel.
// If the article has an image, sendPhoto is used; otherwise sendMessage.
func PostArticle(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	videoURL := strings.TrimSpace(article.VideoURL)
	imageURL := strings.TrimSpace(article.ImageURL)

	if videoURL != "" {
		video := tgbotapi.VideoConfig{
			BaseFile: tgbotapi.BaseFile{
				BaseChat: tgbotapi.BaseChat{ChannelUsername: channelID},
				File:     tgbotapi.FileURL(videoURL),
			},
			Caption:   buildCaption(&article, 1024),
			ParseMode: "HTML",
		}
		if _, err := bot.Send(video); err == nil {
			return nil
		} else {
			slog.Warn("telegram publish media send failed",
				"mode", "publish",
				"step", "send_video",
				"article_id", article.ID,
				"video_url", videoURL,
				"error", err,
			)
		}
	}

	if imageURL != "" {
		photo := tgbotapi.PhotoConfig{
			BaseFile: tgbotapi.BaseFile{
				BaseChat: tgbotapi.BaseChat{
					ChannelUsername: channelID,
				},
				File: tgbotapi.FileURL(imageURL),
			},
			Caption:   buildCaption(&article, 1024),
			ParseMode: "HTML",
		}
		if _, err := bot.Send(photo); err != nil {
			slog.Warn("telegram publish media send failed",
				"mode", "publish",
				"step", "send_photo",
				"article_id", article.ID,
				"image_url", imageURL,
				"error", err,
			)
			// Continue to text/video-link fallback below.
		} else {
			return nil
		}
	}

	if videoURL != "" {
		// YouTube page URLs often fail in sendVideo because they are not direct file URLs.
		if err := sendTextWithVideoLink(bot, channelID, article); err == nil {
			return nil
		} else {
			slog.Warn("telegram publish media fallback failed",
				"mode", "publish",
				"step", "send_text_with_video_link",
				"article_id", article.ID,
				"video_url", videoURL,
				"error", err,
			)
		}
	}

	return sendText(bot, channelID, article)
}

func sendTextWithVideoLink(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	caption := buildCaption(&article, 3800)
	videoURL := strings.TrimSpace(article.VideoURL)
	text := caption + "\n\n" + videoURL

	// tgbotapi v5 does not expose LinkPreviewOptions, so send raw API payload.
	type linkPreviewOptions struct {
		URL              string `json:"url"`
		PreferLargeMedia bool   `json:"prefer_large_media"`
		ShowAboveText    bool   `json:"show_above_text"`
	}
	type payload struct {
		ChatID             string             `json:"chat_id"`
		Text               string             `json:"text"`
		ParseMode          string             `json:"parse_mode"`
		LinkPreviewOptions linkPreviewOptions `json:"link_preview_options"`
	}

	body, err := json.Marshal(payload{
		ChatID:    channelID,
		Text:      text,
		ParseMode: "HTML",
		LinkPreviewOptions: linkPreviewOptions{
			URL:              videoURL,
			PreferLargeMedia: true,
			ShowAboveText:    true,
		},
	})
	if err != nil {
		return fmt.Errorf("marshal payload: %w", err)
	}

	url := fmt.Sprintf("https://api.telegram.org/bot%s/sendMessage", bot.Token)
	resp, err := http.Post(url, "application/json", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("telegram sendMessage with video link: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("telegram api error %d: %s", resp.StatusCode, string(raw))
	}
	return nil
}

func sendText(bot *tgbotapi.BotAPI, channelID string, article db.Article) error {
	msg := tgbotapi.NewMessageToChannel(channelID, buildCaption(&article, 4096))
	msg.ParseMode = "HTML"
	if _, err := bot.Send(msg); err != nil {
		return fmt.Errorf("telegram sendMessage: %w", err)
	}
	return nil
}

// buildCaption forms the final post text based on source type.
func buildCaption(article *db.Article, maxLen int) string {
	var prefix string
	switch article.SourceType {
	case "official":
		prefix = "📢 <b>ОФІЦІЙНО</b>\n\n"
	case "insider":
		prefix = "🕵️ <i>Інсайд</i>\n\n"
	case "aggregator":
		prefix = "📡 <i>Чутки</i>\n\n"
	default:
		prefix = ""
	}

	body := stripSourceFooter(article.BodyUA)
	full := prefix + body
	runes := []rune(full)
	if len(runes) <= maxLen {
		return full
	}

	bodyRunes := []rune(body)
	allowed := maxLen - len([]rune(prefix)) - 3
	if allowed > 0 && allowed < len(bodyRunes) {
		return prefix + string(bodyRunes[:allowed]) + "..."
	}
	return string(runes[:maxLen])
}

// stripSourceFooter removes stray inline-link lines (🔗) left from older
// bot versions. "Джерело:" lines are now generated by the AI and are kept.
func stripSourceFooter(body string) string {
	lines := strings.Split(body, "\n")
	kept := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "🔗") {
			continue
		}
		kept = append(kept, line)
	}
	return strings.TrimSpace(strings.Join(kept, "\n"))
}
